export const VOICE_EVENTS = {
    VOICE_STARTED: 'VOICE_STARTED',
    VOICE_STOPPED: 'VOICE_STOPPED',
    VOICE_TRANSCRIPT: 'VOICE_TRANSCRIPT',
    VOICE_COMMAND: 'VOICE_COMMAND',
    VOICE_RESPONSE: 'VOICE_RESPONSE',
    VOICE_ERROR: 'VOICE_ERROR'
};
