export const sessionEvents = {
    TAB_CREATED: 'TAB_CREATED',
    TAB_UPDATED: 'TAB_UPDATED',
    TAB_REMOVED: 'TAB_REMOVED',
    SESSION_UPDATED: 'SESSION_UPDATED',
    SESSION_ANALYZED: 'SESSION_ANALYZED',
    GRAPH_UPDATED: 'GRAPH_UPDATED'
};
