/**
 * Centralized Event Types Registry
 * Prevents hardcoded magic strings across the extension and web app.
 */
export const EventTypes = {
  // App Lifecycle
  APP_INITIALIZED: 'APP_INITIALIZED',
  BACKGROUND_READY: 'BACKGROUND_READY',
  CONTENT_READY: 'CONTENT_READY',
  SIDEPANEL_READY: 'SIDEPANEL_READY',
  POPUP_READY: 'POPUP_READY',

  // Page Lifecycle
  PAGE_CHANGED: 'PAGE_CHANGED',
  TAB_CHANGED: 'TAB_CHANGED',
  TAB_ACTIVATED: 'TAB_ACTIVATED',
  URL_CHANGED: 'URL_CHANGED',
  PAGE_LOADED: 'PAGE_LOADED',
  PAGE_UNLOADED: 'PAGE_UNLOADED',
  PAGE_VISIBILITY_CHANGED: 'PAGE_VISIBILITY_CHANGED',

  // Extraction Pipeline
  PAGE_EXTRACTED: 'PAGE_EXTRACTED',
  PAGE_EXTRACTION_FAILED: 'PAGE_EXTRACTION_FAILED',
  PDF_UPLOADED: 'PDF_UPLOADED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',

  // Selection
  SELECTION_CHANGED: 'SELECTION_CHANGED',
  TEXT_SELECTED: 'TEXT_SELECTED',
  TEXT_CLEARED: 'TEXT_CLEARED',

  // Voice
  VOICE_STARTED: 'VOICE_STARTED',
  VOICE_STOPPED: 'VOICE_STOPPED',
  VOICE_ERROR: 'VOICE_ERROR',

  // Chat & AI
  CHAT_STARTED: 'CHAT_STARTED',
  CHAT_STREAM: 'CHAT_STREAM',
  CHAT_FINISHED: 'CHAT_FINISHED',
  AGENT_STARTED: 'AGENT_STARTED',
  AGENT_FINISHED: 'AGENT_FINISHED',
  RAG_READY: 'RAG_READY',

  // Data & State
  WORKSPACE_UPDATED: 'WORKSPACE_UPDATED',
  WORKSPACE_SAVED: 'WORKSPACE_SAVED',
  MEMORY_UPDATED: 'MEMORY_UPDATED',
  KNOWLEDGE_UPDATED: 'KNOWLEDGE_UPDATED',

  // Network & Messaging
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  ERROR_OCCURRED: 'ERROR_OCCURRED'
};

export default EventTypes;
