export const knowledgeEvents = {
    DOCUMENT_IMPORTED: 'DOCUMENT_IMPORTED',
    DOCUMENT_INDEXED: 'DOCUMENT_INDEXED',
    EMBEDDINGS_CREATED: 'EMBEDDINGS_CREATED',
    SEARCH_STARTED: 'SEARCH_STARTED',
    SEARCH_COMPLETED: 'SEARCH_COMPLETED',
    KNOWLEDGE_UPDATED: 'KNOWLEDGE_UPDATED'
};
